### ISSUE TITLE
OSTech Project Naming

### ISSUE THREAD

**Issue by SealsRock12** [os-tech-project/oep#1]
# OEP-0001: OSTech Project Naming

## Info

  **Title**: OSTech Project Naming  
  **Author**: @supremestdoggo 
  **Regarding**: OSTech  
  **Created**: 2022--01--06

## Content

OSTech projects should be named in the format `<letter>Tech`, where `<letter>` is decided alphabetically. The first OSTech project was named ATech (which was originally AoPSTech but was changed in order to not infinge on AoPS' trademark), so the next will be BTech. The one after that will be CTech, so on and so forth. OSTech projects can also gain 'proper' names as replacements for the barebones `<letter>Tech` names.

**Comment by SealsRock12** [comment]
This was already in the directory before I created the issue, so I thought I might as well add it to keep the numberings consistent.
@supremestdoggo should we close OEPs once they're approved?

**Comment by supremestdoggo** [comment]
Yep.

**Comment by SealsRock12** [comment]
Also, if OEP-0002 gets denied, and the third OEP gets approved, will we name it OEP-0003 or OEP-0002? I think the former is better to keep it consistent with issue numbers.

**Comment by supremestdoggo** [comment]
A. I say we name it OEP-0002, since it's _approved OEP number 2_.
B. I'd rather you not add them. The point isn't so much to have OEP numbers consistent with issue numbers, but rather to have them be like PEPs, where proposal 20 comes after proposal 19.

**Comment by epiccakeking** [comment]
Perhaps we could have proposals be assigned their OEP numbers once approved, and otherwise simply have them be unnamed proposals?

**Comment by SealsRock12** [comment]
How will we link an OEP to its respective issue then, for discussion about it? Another reason for making it not in sequence is that, if we decide one is not necessary anymore, we can just delete the file and not worry about changing the names of the following ones.

**Comment by SealsRock12** [comment]
Also, @supremestdoggo can you make the OEP into an issue template? We don't have permission to do that.

**Comment by epiccakeking** [comment]
> How will we link an OEP to its respective issue then, for discussion about it? Another reason for making it not in sequence is that, if we decide one is not necessary anymore, we can just delete the file and not worry about changing the names of the following ones.

I think issues can be renamed to include the number in the title (or we could just link it in the OEP itself).

As for deleting OEPs, I don't think that is a good idea since then any references to it will turn up nothing. It would be better to simply note that the OEP is obsolete.

**Comment by supremestdoggo** [comment]
I added an issue template. Also, I'll update the format (and template) to add an **Issue (and/or PR)** section for discussion, as well as a **Status** section. The **Status** section has x options: To do, In development, Implemented, and Rejected. If an OEP is complete, it will be Implemented, and if it's discarded after approval, it will be Rejected.

P.S.: Pretty funny how I'm finishing this right after @epiccakeking added their post.

**Comment by VibraniumWolf** [comment]
Hi! BTW, this is MathGeek16. 

What is an OEP? Also I think the Atech, Btech idea sounds good until we get our final product, and then we can name it something else.

**Comment by SealsRock12** [comment]
It's in the readme:
> OSTech Enhancement Proposals. OEPs should be proposed in issues and propose new features or rules for an OSTech project.

**Comment by supremestdoggo** [comment]
I've changed the format and OEP-0001.
